config/routes.rb
PlatForms2011::Application.routes.draw do
  namespace :admin do 
    resources :categories 
  end

  devise_for :users
  
  root :to => "welcome#hello"
  
  resources :users, :only => [:search, :show] do 
    collection do 
      get :search
    end
  end

  resources :conferences do
    collection do 
      get :search
    end
    match "ical" => "conferences#ical"
    resources :conference_participations
  end

  resource :notifications, :only => [:create, :destroy]

  resources :friendship_requests do
    collection do
      post :send_many
    end
    member do
      post 'confirm'
      post 'reject'
    end
  end
  
  resources :categories, :only => [:show]
  
  scope "ws", :as => "ws", :defaults => { :format => 'json' } do
    resources :conferences, :only => [:create, :show, :update, :index, :destroy] do
      resources :attendees, :only => [:index, :create, :destroy]
    end
    resources :users, :path => "members", :only => [:create, :show, :update] do
      resources :contacts, :only => [:create, :index]
    end
    resources :categories, :only => [:index, :show, :create] do
      member do
        get :conferences
      end
    end
    resources :series, :only => [:index, :show, :create]
    match "/conferencesbycategory/:id" => "categories#conferences"
    match "/search" => "search#search"
    match "/reset" => "maintenance#reset"
    match "/factorydefaults" => "maintenance#factorydefaults"    
  end
  
  

end

app/models/user.rb
# origin: GM
class User < ActiveRecord::Base

  NO_CONTACT = 0
  RCD_SENT = 1
  RCD_RECEIVED = 2
  IN_CONTACT = 3

  attr_accessor :login
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :full_name, :country, 
                  :city, :username, :gps, :login
                  
  validates_presence_of :full_name
  validates_presence_of :email
  validates_presence_of :username
  validates_presence_of :city
  validates_presence_of :country

  validates_uniqueness_of :username

  has_many :friendships
  has_many :friends, :through => :friendships, :conditions => {:friendships => {:status => Friendship::CONFIRMED }}

  has_many :friendship_requests, :class_name => "Friendship", :foreign_key => "user_id", :conditions => {:friendships => {:status => Friendship::OUTSTANDING }}
  has_many :friendship_invitations, :class_name => "Friendship", :foreign_key => "friend_id", :conditions => {:friendships => {:status => Friendship::OUTSTANDING }}
  
  has_many :conference_participations
  has_many :conferences, :through => :conference_participations
  
  has_many :series_contacts, :foreign_key => :contact_id
  has_many :series, :through => :series_contacts
  
  has_many :sent_notifications, :class_name => 'Notification', :foreign_key => "user_id"
  has_many :received_notifications, :class_name => 'Notification', :foreign_key => "receiver_id", :order => 'updated_at DESC'
  
  has_many :organizing_conferences, :class_name => "Conference", :foreign_key => :organizator_id

  class << self
    def find_by_term(term, current_user)
      quoted_term = connection.quote("#{term}%")
      find_by_sql(<<-EOT)
      select 
        u.*,
        IF(ISNULL(f.friend_id), null, true) as is_friend
      from 
        users u 
          left outer join friendships f on (f.friend_id = #{current_user.id} and u.id = f.user_id and f.status = 1)
      group by 
        u.id, f.friend_id
      having
        username like #{quoted_term} OR (is_friend AND full_name like #{quoted_term})
      order by 
        username
      EOT
    end
  end

  def request_friendship(friend)
    self.friendships.create(:friend => friend)
  end
  
  def friend_state(other_user)
    return IN_CONTACT if self == other_user
    
    if friendships.confirmed.map(&:friend).include? other_user
      IN_CONTACT 
    elsif  friendships.outstanding.map(&:friend).include? other_user 
      RCD_SENT
    elsif other_user.friendships.outstanding.map(&:friend).include? self
      RCD_RECEIVED 
    else
      NO_CONTACT
    end
  end
  
  def full_friendships(current_user)
    if self == current_user
      friends + friendship_invitations.outstanding.map(&:user) + friendship_requests.outstanding.map(&:friend)
    else
      friends
    end
  end

  def process_friendship_request(other_user, params)
    if friendship_request = friendship_invitations.outstanding.where(:friendships => {:user_id => other_user.id } ).first
      params["positive"] ? friendship_request.confirm! : friendship_request.reject!
    elsif params["positive"] && !in_contact?(other_user)
      request_friendship(other_user)
    end
  end
  
  def in_contact?(other_user)
    friend_state(other_user) != NO_CONTACT
  end
  
  def friends_with?(other_user)
    friend_state(other_user) == IN_CONTACT
  end

  def attend!(conference)
    conference_participations.create!(:conference => conference)
  rescue ActiveRecord::RecordNotUnique => e
    conference_participations.find_by_conference_id(conference.id)
  end
  
  def wont_attend!(conference)
    attending = conference_participations.detect { |cp| cp.conference == conference }
    attending.destroy if attending
  end
  
  def email=(email)
    write_attribute(:email, email.strip) unless email.nil?
  end
  
  def country=(country)
    unless country.blank?
      write_attribute(:country_code, GPS.geocode(country)[:country_code])
    else
      write_attribute(:country_code, nil)
    end
    write_attribute(:country, country)
  end
  
  def town=(town)
    self.city = town
  end
  
  def participation_for(conference)
    conference_participations.detect { |cp| cp.conference == conference }
  end

  def has_invitation_for(conference)
    received_notifications.detect { |notification| notification.subject == conference }
  end
  
  def gps=(gps)
    unless gps.blank?
      lat, lng = GPS.lat_lng_from_string(gps)
      write_attribute(:lat, lat)
      write_attribute(:lng, lng)
    else
      write_attribute(:lat, nil)
      write_attribute(:lng, nil)
    end
    write_attribute(:gps, gps)
  end
  
  def to_param
    username
  end
  
  def create_conference_invitation_for(user, conference)
    sent_notifications.create(:receiver => user, :subject => conference)
  end
  
  def admin?
    username == "admin"
  end

  protected
    def self.find_for_database_authentication(conditions)
      login = conditions.delete(:login)
      where(conditions).where(["username = :value OR email = :value", { :value => login }]).first
    end
end

app/controllers/users_controller.rb
#origin: M
class UsersController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :load_user, :only => [:show, :update]
  
  def show
    respond_to do |format|
      format.html {  }
      format.json { render :json => @user.to_json }
    end
  end
  
  def search
    @user = User.new(params[:user])
    @empty_form = params[:user].blank?
    
    unless @empty_form
      @users = User.find_by_term(@user.username, current_user)
    else
      @users = []
    end
  end
  
  def update
    if current_user == @user && @user.update_attributes(parse_raw_json)
      render :json => @user.to_json
    elsif current_user != @user
      render :json => "Forbidden", :status => 403
    else
      render :json => "Bad Request", :status => 400
    end
  end
  
  def create
    @user = User.new(parse_raw_json)
    if @user.save
      render :json => @user.to_json
    else
      render :json => "Bad Request", :status => 400
    end
  end
  
  private
    def load_user
      @user = User.find_by_username(params[:id])
      raise ActiveRecord::RecordNotFound unless @user
    end
end

app/views/users/search.html.haml
%h1 Search for a member
= simple_form_for(@user, :url => search_users_path, :html => {:method => :get}) do |f|
  .inputs
    = f.input :username

  .actions
    = f.submit 'Search'
%p
- if !@empty_form
  %h2 Results
  - if @users.empty?
    %p.warn No users found.
  - else
    = form_tag send_many_friendship_requests_path do |f|
      %ul
      - for user in @users
        %li
          %span.checkbox
            - if !current_user.friends_with?(user) && !current_user.friendship_requests.map(&:friend).include?(user)
              = check_box_tag "user[#{user.id}]", 1
            - else
              &nbsp;
          = link_to user_info(user), user
          = "( #{user.city}, #{user.country} )"
      = submit_tag "Make friends!", :class => 'make_friends'

app/views/users/show.html.haml
%h1
  - if @user == current_user
    Your Profile
  - else
    Profile of
    = current_user.friends_with?(@user) ? @user.full_name : @user.username

- if current_user == @user
  %h2 Notifications
  - if @user.received_notifications.empty?
    %p.warn No notifications.
  - else
    %ul.links
      - for notification in @user.received_notifications
        %li
          = display_notification(notification)
  %h2 Friendship invitations
  - if @user.friendship_invitations.empty?
    %p.warn No friendship invitations.
  - else
    %ul.links
      - for friendship in @user.friendship_invitations
        %li
          = button_to 'Confirm!', confirm_friendship_request_path(friendship), :class => 'confirm_friendship'
          = button_to 'Reject!', reject_friendship_request_path(friendship), :class => 'reject_friendship', :confirm => "You don't want to be friends?" 
          \-
          = link_to friendship.user.full_name, friendship.user 

%h2 Details
%table
  %tr
    %td Username:
    %td= @user.username
  - if current_user.friends_with?(@user)
    %tr
      %td Full name:
      %td= @user.full_name
    %tr
      %td Email:
      %td= @user.email
  %tr
    %td Town:
    %td= @user.city
  %tr
    %td Country:
    %td= @user.country
  %tr
    %td Latitude:
    %td= @user.lat
  %tr
    %td Longitude:
    %td= @user.lng
    

%h2 Friends
- if @user.friends.empty?
  %p.warn
    - if current_user == @user
      Uhh? You have no friends here!
      = link_to 'Make some.', search_users_path
    - else
      = user_info(@user)
      has no Friends.
- else
  %ul.links
    - for friend in @user.friends
      %li= link_to user_info(friend), friend
        
- if current_user == @user      
  %h2 Friendship request
  - if @user.friendship_requests.empty?
    %p.warn No outstanding friendship requests.
  - else
    %ul.links
      - for friend in @user.friendship_requests.map(&:friend)
        %li= link_to user_info(friend), friend
  
  %h2 Your personal calender
  %p
    %span.warn
      You have not added any conferences to your calender so it's not displayed.
    %br
    (Adding conferences to the personal calender is not a MUST in the specification. ;)
      
    