config/routes.rb
PlatForms2011::Application.routes.draw do
  namespace :admin do 
    resources :categories 
  end

  devise_for :users
  
  root :to => "welcome#hello"
  
  resources :users, :only => [:search, :show] do 
    collection do 
      get :search
    end
  end

  resources :conferences do
    collection do 
      get :search
    end
    match "ical" => "conferences#ical"
    resources :conference_participations
  end

  resource :notifications, :only => [:create, :destroy]

  resources :friendship_requests do
    collection do
      post :send_many
    end
    member do
      post 'confirm'
      post 'reject'
    end
  end
  
  resources :categories, :only => [:show]
  
  scope "ws", :as => "ws", :defaults => { :format => 'json' } do
    resources :conferences, :only => [:create, :show, :update, :index, :destroy] do
      resources :attendees, :only => [:index, :create, :destroy]
    end
    resources :users, :path => "members", :only => [:create, :show, :update] do
      resources :contacts, :only => [:create, :index]
    end
    resources :categories, :only => [:index, :show, :create] do
      member do
        get :conferences
      end
    end
    resources :series, :only => [:index, :show, :create]
    match "/conferencesbycategory/:id" => "categories#conferences"
    match "/search" => "search#search"
    match "/reset" => "maintenance#reset"
    match "/factorydefaults" => "maintenance#factorydefaults"    
  end
  
  

end

app/models/conference.rb
# origin: M
class Date
  def to_i
    to_s(:db).gsub("-", '').to_i
  end
end

# FIXME!
WebMock.disable_net_connect!(:allow_localhost => true) if defined? WebMock

class Conference < ActiveRecord::Base
  belongs_to :series
  
  belongs_to :creator, :foreign_key => :organizator_id, :class_name => 'User'
  
  has_many :conference_participations, :dependent => :destroy
  has_many :participants, :through => :conference_participations, :source => :user
  has_many :conference_categories, :dependent => :destroy
  has_many :categories, :through => :conference_categories
  
  belongs_to :organizator, :class_name => "User"

  validates_presence_of :name
# FIXME startdate < enddate
  validates_presence_of :startdate
  validates_presence_of :enddate
# FIXME  validates_presence_of :categories
  validates_presence_of :description
  validates_presence_of :location
  validates_presence_of :creator
  
  default_scope :order => 'startdate ASC'
  
  scope :running, :conditions => ['startdate <= CURDATE() AND enddate >= CURDATE()']
  scope :tomorrow, :conditions => ['startdate = CURDATE() + 1']
  
  searchable do 
    text :name
    text :description     
    integer :category, :multiple => true, :using => :category_ids

    integer :open_on, :multiple => true, :using => :open_on_date_numbers
    
    # string :country_code
    
    location :coordinates do
      self
    end
  end
  
  def open_on_date_numbers
    (startdate..enddate).to_a.map(&:to_i)
  end
  
  def category_ids
    categories.map(&:id)
  end

  class << self
    def query(opts)
      term = opts.delete(:term)
      startdate = opts.delete(:startdate)
      enddate = opts.delete(:enddate)
      
      if categories = opts.delete(:categories)
        if opts.delete(:include_subcategories)
          categories = categories.map(&:self_with_ancestors).flatten
        end
      end
      
      solr = Conference.search do
        keywords(term) if term
        with(:category).any_of(categories.map(&:id)) if categories and categories.any?
        with(:open_on).greater_than(startdate.to_i) if startdate
        with(:open_on).less_than(enddate.to_i) if enddate

        # with(:coordinates).near(BigDecimal.new('40.7'), BigDecimal.new('-73.5'))
        # with(:enddate).less_equal(enddate) if enddate
        # with(:coordinates).near(a.lat.to_f, a.lng.to_f, :precision => 10) 
      end
      solr.results
    end
    
    def build_from_json(conference_hash, user)
      categories = conference_hash.delete("categories")
      conference = new(conference_hash)
      conference.organizator = user
      if categories 
        categories = categories.map do |category|
          Category.find_by_name(category["name"])
        end
        conference.categories << categories
      end
      conference
    end
    
  end
  
  def update_from_params(params) 
    if params[:format] == "json"
      self.attributes = JSON.parse(params[:conference])
    else
      self.attributes = params[:conference]
    end
    save!
  end
  
  def location=(location)
    write_attribute(:location, location)
    geo_location = GPS.geocode(location)
    write_attribute(:city, geo_location[:city])
    write_attribute(:country_code, geo_location[:country_code])
    location
  end

  def gps=(gps)
    unless gps.blank?
      lat, lng = GPS.lat_lng_from_string(gps)
      write_attribute(:lat, lat)
      write_attribute(:lng, lng)
    else
      write_attribute(:lat, nil)
      write_attribute(:lng, nil)
    end
    write_attribute(:gps, gps)
  end
end

app/controllers/conferences_controller.rb
#origin M
class ConferencesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :throw_not_implemented_for_json, :only => [:index, :destroy]
  
  def create
    respond_to do |format|
      
      format.json do
        begin
          @conference = current_user.organizing_conferences.build_from_json(parse_raw_json, current_user)
          if @conference.save
            render :json => @conference.to_json 
          else
            render :status => 400, :json => "Cannot save!"
          end
        rescue ActiveRecord::UnknownAttributeError
          render :status => 400, :json => "Cannot save!"
        end
      end
      
      format.html do
        @conference = current_user.organizing_conferences.build(params[:conference])
        if @conference.save
          redirect_to(conference_path(@conference), :notice => 'Conference was successfully created.')
        else
          render :action => "new" 
        end
      end
    end
  end

  def index
    @conferences = Conference.all
    respond_to do |format|
      format.html { }
    end
  end

  def show
    @conference = Conference.find(params[:id])
    respond_to do |format|
      format.html { }
      format.json { render :json => @conference.to_json }
    end
  end
  
  def search
    @conference = Conference.new(params[:conference])
    @empty_form = params[:commit].blank?
    
    unless @empty_form
      @conferences = Conference.query(
        :term => @conference.name, 
        :startdate => @conference.startdate,
        :enddate => @conference.enddate,
        :categories => @conference.categories,
        :include_subcategories => params[:include_subcategories] == "1"
      )
    else
      @conferences = []
    end
  end
  
  def update
    @conference = current_user.organizing_conferences.find(params[:id]) 
    @conference.attributes = params[:conference] || parse_raw_json
    respond_to do |format|
      format.json do
        if @conference.save
          render :json => @conference.to_json
        end
      end
    
      format.html do
        if @conference.save
          redirect_to(conference_path(@conference), :notice => 'Conference was successfully updated.')
        end
      end
    end
  end
  
  def new
    @conference = Conference.new
  end

  def edit
    @conference = current_user.organizing_conferences.find(params[:id])
  end
  
  def ical
    conference = Conference.find(params[:conference_id])
    
    cal = Icalendar::Calendar.new
    cal.event do
      dtstart     conference.startdate
      dtend       conference.enddate
      summary     conference.name
      description conference.description
    end
    
    headers['Content-Type'] = "text/calendar; charset=UTF-8"
    render :text => cal.to_ical, :layout => false
  end
  
  protected 
    def throw_not_implemented_for_json
      if params[:format] == 'json'
        render :status => 501, :text => "Not Implemented" and return false
      end
    end
  
end

app/helpers/conferences_helper.rb
module ConferencesHelper
  def attend_or_unattend_button
    if participation = current_user.participation_for(@conference)
      button_to("Won't attend!!", conference_conference_participation_path(@conference, participation), :method => :delete)
    else
      button_to("Attend!", conference_conference_participations_path(@conference), :method => :post)
    end
  end
  
  def conference_link(conference)
    ("#{conference.startdate} to #{conference.enddate} - " + link_to(conference.name, conference_path(conference))).html_safe
  end
  
  def edit_link_if_creator(user)
    return unless @conference.creator == user
      
    button_to("Edit this conference", edit_conference_path(@conference), :method => :get, :id => :conference_edit)
  end
end

app/views/conferences/_form.html.haml
%p
  = simple_form_for(@conference) do |f|
    - if @conference.errors.any?
      #error_explanation
        %h2
          = pluralize(@conference.errors.count, "error")
          prohibited this conference from being saved:

        %ul
        - @conference.errors.full_messages.each do |msg|
          %li= msg

    .inputs
      = f.input :name
      = f.input :startdate
      = f.input :enddate
      = f.input :description
      = f.input :location

      = f.input :gps
      = f.association :categories, :collection => Category.for_select
      = f.input :venue
      = f.input :accomodation
      = f.input :howtofind

    .actions
      = f.button :submit

app/views/conferences/edit.html.haml
%h1 Editing conference

= render 'form'
= link_to 'Back', conference_path(@conference)

app/views/conferences/index.html.haml
%h1 Listing conferences

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @conferences.each do |conference|
    %tr
      %td= conference.name
      %td= link_to 'Show', conference
      %td= link_to 'Edit', edit_conference_path(conference)

%br

= link_to 'New Conference', new_conference_path

app/views/conferences/new.html.haml
%h1 Add conference

= render 'form'

app/views/conferences/search.html.haml
%h1 Search for a conference
= simple_form_for(@conference, :url => search_conferences_path, :html => {:method => :get}) do |f|
  .inputs
    = f.input :name
    = f.input :startdate, :include_blank => true
    = f.input :enddate, :include_blank => true
    = f.association :categories, :collection => Category.for_select
    %label With sub-categories
    = check_box_tag 'include_subcategories', 1, params['include_subcategories']

  .actions
    = f.submit 'Search'
%p
- if !@empty_form
  %h2 Results
  - if @conferences.empty?
    %p.warn No results. Sorry :,(
  - else
    %ul.links
      - for conference in @conferences
        %li= conference_link(conference)

app/views/conferences/show.html.haml
%h1= @conference.name

%p.subline
  from
  = @conference.startdate
  to
  = @conference.enddate
  in
  = @conference.location
  %span.ical
    (
    = link_to "iCal", conference_ical_path(@conference)
    )

  - if current_user.participation_for(@conference)
    %br
    %span.warn You are attending the conference.
  - if current_user == @conference.creator
    %br
    %span.warn You are the organizator.

%h2 Description
%p= @conference.description

- unless @conference.venue.blank?
  %h2 Venue
  %p= @conference.venue

- unless @conference.howtofind.blank?
  %h2 How to find
  %p= @conference.howtofind

- unless @conference.accomodation.blank?
  %h2 Accomodation
  %p= @conference.accomodation
  
%h2 Organizer
%p
  = link_to @conference.creator.full_name, user_path(@conference.creator)
  (
  = link_to @conference.creator.email, "mailto:#{@conference.creator.email}"
  )
  = edit_link_if_creator(current_user)

%h2 Attendees
- unless @conference.participants.empty?
  %ul.links
    - for participant in @conference.participants
      %li= link_to user_info(participant), user_path(participant)
- else
  %p.warn No attendees so far
%p= attend_or_unattend_button

%h2 Categories
%p= @conference.categories.map(&:name).join(', ')

%h2 Invite friends
- if current_user.friends.any?
  %ul.links
    = form_tag notifications_path do |f|
      = hidden_field_tag :conference_id, @conference.id
      - for friend in current_user.friends
        %li
          %span.checkbox
            - unless friend.participation_for(@conference) || friend.has_invitation_for(@conference) 
              = check_box_tag "user[#{friend.id}]", 1
            - else
              %span.warn IV
          = link_to user_info(friend), user_path(friend)
      = submit_tag "Invite friends to this conference!", :class => 'invite_friends_to_conference'
    