config/routes.rb
PlatForms2011::Application.routes.draw do
  namespace :admin do 
    resources :categories 
  end

  devise_for :users
  
  root :to => "welcome#hello"
  
  resources :users, :only => [:search, :show] do 
    collection do 
      get :search
    end
  end

  resources :conferences do
    collection do 
      get :search
    end
    match "ical" => "conferences#ical"
    resources :conference_participations
  end

  resource :notifications, :only => [:create, :destroy]

  resources :friendship_requests do
    collection do
      post :send_many
    end
    member do
      post 'confirm'
      post 'reject'
    end
  end
  
  resources :categories, :only => [:show]
  
  scope "ws", :as => "ws", :defaults => { :format => 'json' } do
    resources :conferences, :only => [:create, :show, :update, :index, :destroy] do
      resources :attendees, :only => [:index, :create, :destroy]
    end
    resources :users, :path => "members", :only => [:create, :show, :update] do
      resources :contacts, :only => [:create, :index]
    end
    resources :categories, :only => [:index, :show, :create] do
      member do
        get :conferences
      end
    end
    resources :series, :only => [:index, :show, :create]
    match "/conferencesbycategory/:id" => "categories#conferences"
    match "/search" => "search#search"
    match "/reset" => "maintenance#reset"
    match "/factorydefaults" => "maintenance#factorydefaults"    
  end
  
  

end

app/models/category.rb
#origin: M
class Category < ActiveRecord::Base
  belongs_to :parent, :class_name => 'Category'
  has_many :sub_categories, :class_name => 'Category', :foreign_key => 'parent_id'
  
  has_many :conference_categories
  has_many :conferences, :through => :conference_categories
  
  scope :root, :conditions => 'parent_id is NULL'
  
  validates_presence_of :name
  
  class << self
    def for_select
      all.map { |cat| [cat.full_name, cat.id ] }.sort_by { |c| c[0] }
    end
  end
  
  def conferences_including_subs(conferences = [])
    conferences << self.conferences
    sub_categories.each { |category| category.conferences_including_subs(conferences) }
    conferences.flatten.uniq
  end
  
  def full_name
    if parent 
      "#{parent.full_name} : #{name}"
    else
      name
    end
  end
  
  def self_with_ancestors
    [self, sub_categories.map(&:self_with_ancestors)].flatten
  end
end

app/controllers/admin/categories_controller.rb
# origin: M
class Admin::CategoriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :ensure_admin!
  
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      redirect_to(admin_categories_path, :notice => 'Category was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to(admin_categories_path, :notice => 'Category was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to(admin_categories_url) 
  end
end

app/controllers/categories_controller.rb
#origin M
class CategoriesController < ApplicationController

  before_filter :authenticate_user!, :except => [:show]
  before_filter :ensure_admin!, :only => [:create]
  
  def index
    @categories = Category.root.all
    render :json => @categories.to_json, :status => (@categories.blank? ? 204 : 200)
  end
  
  def show
    @category = Category.find(params[:id])
    
    respond_to do |format|
      format.html { render :action => 'show' }
      format.json { render :json => @category.to_json }
    end
  end
  
  def conferences
    @category = Category.find(params[:id])
    @conferences = @category.conferences
    render :json => @conferences.to_json, :status => (@categories.blank? ? 204 : 200)
  end
  
  def create
    @category = Category.new(parse_raw_json)
    if @category.save
      render :json => @category.to_json
    else
      render :json => "", :status => 400
    end
  rescue ActiveRecord::UnknownAttributeError => e
    render :json => "", :status => 400    
  end

end

app/views/admin/categories/_form.html.haml
= simple_form_for(@category, :url => @category.new_record? ? admin_categories_url : admin_category_url) do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:

      %ul
      - @category.errors.full_messages.each do |msg|
        %li= msg

  .inputs
    = f.input :name
    = f.association :parent

  .actions
    = f.button :submit

%p
  = link_to 'Back to categories', admin_categories_path

app/views/admin/categories/edit.html.haml
%h1 Editing admin_category

= render 'form'

app/views/admin/categories/index.html.haml
%h1 Listing categories

%table
  %tr
    %th Name
    %th Parent

  - @categories.each do |admin_category|
    %tr
      %td= admin_category.name
      %td= admin_category.parent.try(:name)
      %td= button_to 'Edit', edit_admin_category_path(admin_category), :method => :get

%br

= button_to 'Add category', new_admin_category_path, :method => :get

app/views/admin/categories/new.html.haml
%h1 New admin_category

= render 'form'

app/views/admin/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @admin_category.name
%p
  %b Parent:
  = @admin_category.parent_id

= link_to 'Edit', edit_admin_category_path(@admin_category)
\|
= link_to 'Back', admin_categories_path