config/routes.rb
PlatForms2011::Application.routes.draw do
  namespace :admin do 
    resources :categories 
  end

  devise_for :users
  
  root :to => "welcome#hello"
  
  resources :users, :only => [:search, :show] do 
    collection do 
      get :search
    end
  end

  resources :conferences do
    collection do 
      get :search
    end
    match "ical" => "conferences#ical"
    resources :conference_participations
  end

  resource :notifications, :only => [:create, :destroy]

  resources :friendship_requests do
    collection do
      post :send_many
    end
    member do
      post 'confirm'
      post 'reject'
    end
  end
  
  resources :categories, :only => [:show]
  
  scope "ws", :as => "ws", :defaults => { :format => 'json' } do
    resources :conferences, :only => [:create, :show, :update, :index, :destroy] do
      resources :attendees, :only => [:index, :create, :destroy]
    end
    resources :users, :path => "members", :only => [:create, :show, :update] do
      resources :contacts, :only => [:create, :index]
    end
    resources :categories, :only => [:index, :show, :create] do
      member do
        get :conferences
      end
    end
    resources :series, :only => [:index, :show, :create]
    match "/conferencesbycategory/:id" => "categories#conferences"
    match "/search" => "search#search"
    match "/reset" => "maintenance#reset"
    match "/factorydefaults" => "maintenance#factorydefaults"    
  end
  
  

end

app/views/layouts/application.html.haml
!!! 5
%head
  %title PlatForms2011
  = stylesheet_link_tag 'reset-min.css'
  = stylesheet_link_tag :all
  = stylesheet_link_tag 'application.css'

  = javascript_include_tag :defaults
  = csrf_meta_tag
  = yield(:head)

%body
  #flash
    = render :partial => 'shared/flash'
  #header
    #navigation
      = link_to image_tag('cap.png', :alt => 'CaP', :class => 'logo'), root_path
      %ul.navigation
        - if current_user
          %li= link_to "Search conferences", search_conferences_path, :id => 'search_conferences'
          %li= link_to "Add conference", new_conference_path, :id => 'add_conference'
          %li= link_to "Search members", search_users_path, :id => 'search_members'
          %li= link_to "My profile (#{current_user.username})", user_path(current_user), :id => 'profile'
          %li= link_to "Sign out", destroy_user_session_path, :id => 'sign_out'
        - else
          %li= link_to "Sign in", new_user_session_path
          %li= link_to "Sign up", new_user_registration_path, :id => 'sign_up'
        - if current_user.try(:admin?)
          %li
            \|
            = link_to "Manage categories", admin_categories_path, :id => 'category_admin'
    
  #content
    = yield
  #footer
    CaP Application build by
    = link_to 'tmp8 GmbH', 'http://tmp8.de'
    during Plat_Forms competition in 2011 under MIT license. CaP icon by DaPino - Creative Commons Attribution Non-commercial